import java.util.Arrays;

public class day_4_1_sztringbol {

  public static int[][] súlyozottRendezés(int[][] tömb, int dimenzió,String irány){
    /*for (int i = 0; i < tömb.length; i++) {
      for (int j = 0; j < 2; j++) {
        System.out.print(tömb[i][j]+" ");
      }
      System.out.println("");
    }*/
    if(irány.equals("csökkenő"))
      Arrays.sort(tömb, (int a[], int b[]) -> Integer.compare(b[dimenzió], a[dimenzió]));
    else
      Arrays.sort(tömb, (int a[], int b[]) -> Integer.compare(a[dimenzió], b[dimenzió]));
    return tömb;
  }

  public static int[] egyChksumMeghatározása(int aktGyakoriságNdx, int[][] előfordulások){
    int[] vissza=new int[2];
    return vissza;
  }

  public static String számoltChecksumToString(int[] számoltCheckSum){
    String sztringVissza="";
    for (int i = 0; i < számoltCheckSum.length; i++) {
      sztringVissza=sztringVissza.concat(Character.toString((char)(számoltCheckSum[i])));
    }
    return sztringVissza;
  }
  
  public static void main(String[] args) {
    /*String kódok="aaaaa-bbb-z-y-x-123[abxyz]"+
            "a-b-c-d-e-f-g-h-987[abcde]"+
            "not-a-real-room-404[oarel]"+
            "totally-real-room-200[decoy]";*/
String kódok="bkwzkqsxq-tovvilokx-nozvyiwoxd-172[fstek]\n" +
"wifilzof-wbiwifuny-yhachyylcha-526[qrazx]\n" +
"jvyyvzpcl-jhukf-shivyhavyf-487[zhtsi]\n" +
"kwvacumz-ozilm-kivlg-kwvbiqvumvb-694[gknyw]\n" +
"mvhkvbdib-kmjezxodgz-mvwwdo-omvdidib-837[dmvbi]\n" +
"nzydfxpc-rclop-qwzhpc-lnbftdtetzy-171[cptzd]\n" +
"vhehkyne-unggr-inkvatlbgz-813[gnehk]\n" +
"tcorcikpi-hnqygt-octmgvkpi-570[nzewo]\n" +
"xmtjbzidx-wvnfzo-jkzmvodjin-447[uyzlp]\n" +
"willimcpy-mwupyhayl-bohn-mufym-734[stjoc]\n" +
"sbejpbdujwf-cvooz-xpsltipq-961[azfnd]\n" +
"jchipqat-qphzti-rjhidbtg-htgkxrt-271[thigj]\n" +
"npmhcargjc-zsllw-pcqcypaf-158[mzwnx]\n" +
"luxciuwncpy-jfumncw-alumm-qilembij-318[mucil]\n" +
"bxaxipgn-vgpst-rpcsn-rdpixcv-htgkxrth-427[ywazt]\n" +
"zekvierkzferc-tyftfcrkv-ivtvzmzex-295[evzfk]\n" +
"enzcntvat-qlr-hfre-grfgvat-143[rtaef]\n" +
"mvkccspson-bkllsd-nofovyzwoxd-224[oscdk]\n" +
"enzcntvat-zvyvgnel-tenqr-pnaql-pbngvat-ratvarrevat-429[zymbs]\n" +
"nwzekwypera-xwogap-pnwejejc-992[lkiwn]\n" +
"ajmrxjlcren-ajkkrc-lxwcjrwvnwc-667[ezynd]\n" +
"bxaxipgn-vgpst-hrpktcvtg-wjci-advxhixrh-661[lytku]\n" +
"owshgfarwv-vqw-kzahhafy-190[ahwfv]\n" +
"jqwpihizlwca-moo-twoqabqka-512[ncdyv]\n" +
"apwmeclga-pyzzgr-rcaflmjmew-886[amceg]\n" +
"tyepcyletzylw-ojp-wzrtdetnd-951[mxqsy]\n" +
"dlhwvupglk-kfl-hjxbpzpapvu-773[nrotd]\n" +
"fab-eqodqf-dmnnuf-bgdotmeuzs-612[dchyk]\n" +
"qjopwxha-bhksan-skngodkl-940[kahno]\n" +
"lsyrkjkbnyec-dyz-combod-cmkfoxqob-rexd-bomosfsxq-718[lktzs]\n" +
"zixppfcfba-bdd-jxohbqfkd-939[sqtor]\n" +
"vxupkizork-kmm-ktmotkkxotm-852[dsqjh]\n" +
"excdklvo-mkxni-mykdsxq-nozkbdwoxd-952[zspmc]\n" +
"bnqqnrhud-eknvdq-sqzhmhmf-391[qhndm]\n" +
"gzefmnxq-otaoaxmfq-ogefayqd-eqdhuoq-716[zinwb]\n" +
"qzoggwtwsr-qobrm-ghcfous-428[goqrs]\n" +
"gpbepvxcv-ltpedcxots-qphzti-steadnbtci-193[ignjy]\n" +
"hvbizodx-nxvqzibzm-cpio-hvmfzodib-265[hixfe]\n" +
"wkqxodsm-lexxi-kxkvicsc-926[xkcis]\n" +
"bknsykmdsfo-myxcewob-qbkno-oqq-zebmrkcsxq-380[utqrz]\n" +
"lejkrscv-wcfnvi-kirzezex-711[ecikr]\n" +
"htwwtxnaj-idj-btwpxmtu-255[itgmd]\n" +
"zsxyfgqj-jll-ijufwyrjsy-931[wrpgt]\n" +
"iuxxuyobk-yigbktmkx-natz-gtgreyoy-384[ygktx]\n" +
"qjopwxha-xqjju-zalhkuiajp-628[esmxk]\n" +
"lxaaxbren-ljwmh-anbnjalq-745[stjqy]\n" +
"gokzyxsjon-zvkcdsm-qbkcc-dbksxsxq-380[tsyqk]\n" +
"qzoggwtwsr-qobrm-qcohwbu-rsdofhasbh-168[obhqr]\n" +
"pelbtravp-pnaql-fgbentr-325[pabel]\n" +
"xzwrmkbqtm-akidmvomz-pcvb-mvoqvmmzqvo-122[mvoqz]\n" +
"sbnqbhjoh-ezf-fohjoffsjoh-233[xskyb]\n" +
"jyddc-yrwxefpi-fewoix-hiwmkr-412[pdekg]\n" +
"fab-eqodqf-rxaiqd-xmnadmfadk-690[sicjl]\n" +
"xcitgcpixdcpa-rpcsn-htgkxrth-427[stznv]\n" +
"rflsjynh-rnqnyfwd-lwfij-jll-xytwflj-229[lfjnw]\n" +
"zotts-wlsiayhcw-vumeyn-fuvilunils-500[ilsun]\n" +
"odiih-yujbcrl-pajbb-dbna-cnbcrwp-147[bcadi]\n" +
"udskkaxawv-tmffq-klgjsyw-996[tmnfc]\n" +
"emixwvqhml-kpwkwtibm-wxmzibqwva-278[zomvn]\n" +
"dfcxsqhwzs-dzoghwq-ufogg-zcuwghwqg-116[kmijn]\n" +
"dwbcjkun-ouxfna-mnbrpw-745[nbuwa]\n" +
"jchipqat-rwdrdapit-pcpanhxh-973[hglvu]\n" +
"fkqbokxqflkxi-avb-zlkqxfkjbkq-861[wdnor]\n" +
"wbhsfbohwcboz-foppwh-qighcasf-gsfjwqs-480[fhswb]\n" +
"dzczkrip-xiruv-szfyrqriuflj-treup-kvtyefcfxp-451[rfipu]\n" +
"fmsledevhsyw-fyrrc-eguymwmxmsr-698[yzoxu]\n" +
"udskkaxawv-jsttal-wfyafwwjafy-840[nlkda]\n" +
"sno-rdbqds-idkkxadzm-sqzhmhmf-287[lngzc]\n" +
"crwwv-yxphbq-rpbo-qbpqfkd-341[bpqrw]\n" +
"odiih-mhn-anjlzdrbrcrxw-563[xadcy]\n" +
"jyddc-ikk-wlmttmrk-698[lmstk]\n" +
"buzahisl-wshzapj-nyhzz-klzpnu-149[pjxor]\n" +
"odkasqzuo-eomhqzsqd-tgzf-ymzmsqyqzf-560[frqmp]\n" +
"gokzyxsjon-bkllsd-yzobkdsyxc-874[nbtmv]\n" +
"excdklvo-pvygob-bocokbmr-952[tyzxa]\n" +
"jvsvymbs-jovjvshal-aljouvsvnf-253[zgtdm]\n" +
"hafgnoyr-qlr-erfrnepu-637[refna]\n" +
"pelbtravp-sybjre-fnyrf-299[tjoim]\n" +
"fodvvlilhg-gbh-vwrudjh-621[hvdgl]\n" +
"kgjgrypw-epybc-bwc-bcnjmwkclr-678[smijy]\n" +
"myxcewob-qbkno-mrymyvkdo-dbksxsxq-458[bkmox]\n" +
"joufsobujpobm-fhh-dpoubjonfou-311[uvksy]\n" +
"rflsjynh-ojqqdgjfs-ijajqturjsy-697[jqsfr]\n" +
"vetllbybxw-vtgwr-kxtvjnblbmbhg-709[athym]\n" +
"ajvyjprwp-ajmrxjlcren-kdwwh-lxwcjrwvnwc-433[qsaxt]\n" +
"zbytomdsvo-mkxni-mykdsxq-myxdksxwoxd-952[xdmko]\n" +
"esyfwlau-bwddqtwsf-suimakalagf-684[stvip]\n" +
"jef-iushuj-fhezusjybu-fbqijys-whqii-huiuqhsx-582[uhijs]\n" +
"tpspahyf-nyhkl-jovjvshal-bzly-alzapun-565[sdprn]\n" +
"apwmeclga-hcjjwzcyl-umpiqfmn-132[shfrg]\n" +
"kwtwznct-jcvvg-lmxizbumvb-148[vbcmt]\n" +
"rmn-qcapcr-aylbw-umpiqfmn-366[juftv]\n" +
"sorozgxe-mxgjk-hgyqkz-yzuxgmk-748[xuvst]\n" +
"bkwzkqsxq-wsvsdkbi-qbkno-mkxni-mykdsxq-yzobkdsyxc-822[ksbqx]\n" +
"ryexqpqhteki-vbemuh-skijecuh-iuhlysu-842[tszmj]\n" +
"ikhcxvmbex-wrx-wxlbzg-501[zhqis]\n" +
"lsyrkjkbnyec-mrymyvkdo-nozvyiwoxd-978[enkfi]\n" +
"wdjcvuvmyjpn-mvhkvbdib-agjrzm-nojmvbz-395[tcxne]\n" +
"uwtojhynqj-gfxpjy-fhvznxnynts-567[kqpvs]\n" +
"iqmbazulqp-pkq-dqoquhuzs-534[ntpuq]\n" +
"gntmfefwitzx-ojqqdgjfs-ijajqturjsy-385[jfqtg]\n" +
"sebehvkb-fhezusjybu-zubboruqd-husuylydw-972[ytsim]\n" +
"nzcczdtgp-nsznzwlep-hzcvdsza-405[yotgu]\n" +
"joufsobujpobm-fhh-ufdiopmphz-675[tsymn]\n" +
"cxy-bnlanc-snuuhknjw-anbnjalq-823[nabcj]\n" +
"shoewudys-rkddo-huiuqhsx-374[dhsuo]\n" +
"vagreangvbany-rtt-jbexfubc-403[ynepo]\n" +
"aoubshwq-dzoghwq-ufogg-aobousasbh-714[oabgh]\n" +
"njmjubsz-hsbef-dipdpmbuf-qvsdibtjoh-805[bdjsf]\n" +
"zovldbkfz-gbiivybxk-lmboxqflkp-653[nyajo]\n" +
"yknnkoera-xwogap-hkceopeyo-628[ybmzc]\n" +
"nij-mywlyn-wbiwifuny-guleyncha-396[nyiwl]\n" +
"ocipgvke-ecpfa-eqcvkpi-vgejpqnqia-258[jsiqz]\n" +
"encuukhkgf-hnqygt-vgejpqnqia-882[dxzer]\n" +
"odiih-ljwmh-anbnjalq-927[ahijl]\n" +
"fkqbokxqflkxi-zxkav-ixyloxqlov-861[nxgja]\n" +
"udskkaxawv-xmrrq-uzgugdslw-sfsdqkak-216[msfyx]\n" +
"owshgfarwv-bwddqtwsf-kzahhafy-216[wafhd]\n" +
"oaxadrgx-dmnnuf-ruzmzouzs-794[uqhse]\n" +
"ziuxioqvo-akidmvomz-pcvb-zmikycqaqbqwv-616[iqvmo]\n" +
"bqvvu-xqjju-opknwca-550[yzhum]\n" +
"xgjougizobk-lruckx-gtgreyoy-670[nbfmk]\n" +
"bxaxipgn-vgpst-uadltg-bpgztixcv-323[gptxa]\n" +
"vcibutulxiom-jfumncw-alumm-nluchcha-448[ucmla]\n" +
"irgyyolokj-xghhoz-uvkxgzouty-930[ogyhk]\n" +
"kyelcrga-aylbw-amyrgle-umpiqfmn-782[almye]\n" +
"jsvagsulanw-xdgowj-kzahhafy-138[dblcm]\n" +
"ixccb-fkrfrodwh-uhdftxlvlwlrq-881[mblzw]\n" +
"chnylhuncihuf-mwupyhayl-bohn-guleyncha-422[hnuyc]\n" +
"irdgrxzex-treup-tfrkzex-uvgrikdvek-165[sjbnk]\n" +
"xzwrmkbqtm-akidmvomz-pcvb-zmikycqaqbqwv-434[sanut]\n" +
"ykhknbqh-zua-iwjwcaiajp-524[kjlio]\n" +
"jlidywncfy-mwupyhayl-bohn-uwkocmcncih-916[cyhnw]\n" +
"nuatmlmdpage-omzpk-eqdhuoqe-326[ljtsm]\n" +
"xmrrq-kusnwfywj-zmfl-suimakalagf-684[afmkl]\n" +
"foadouwbu-qvcqczohs-rsgwub-116[oubcq]\n" +
"etyyx-bgnbnkzsd-kzanqzsnqx-391[pnmlv]\n" +
"pinovwgz-wvnfzo-hvmfzodib-291[ovzfi]\n" +
"qekrixmg-gsrwyqiv-kvehi-fewoix-ywiv-xiwxmrk-828[iwxek]\n" +
"jqwpihizlwca-xtiabqk-oziaa-kcabwumz-amzdqkm-928[aizkm]\n" +
"qekrixmg-jpsaiv-stivexmsrw-672[etmsq]\n" +
"excdklvo-gokzyxsjon-mrymyvkdo-bomosfsxq-562[okmsx]\n" +
"qczcftiz-pibbm-aobousasbh-532[zynvo]\n" +
"wbhsfbohwcboz-suu-gsfjwqsg-506[bdhxv]\n" +
"lxwbdvna-pajmn-ajkkrc-anlnrerwp-563[anrjk]\n" +
"lsyrkjkbnyec-pvygob-cobfsmoc-900[uyrgf]\n" +
"cqwdujys-sxesebqju-ixyffydw-374[nyjvi]\n" +
"odiih-ouxfna-anlnrerwp-433[naior]\n" +
"rzvkjiduzy-xviyt-xjvodib-vxlpdndodji-993[aousd]\n" +
"ltpedcxots-qphzti-rjhidbtg-htgkxrt-453[rjlkn]\n" +
"krxqjijamxdb-kdwwh-fxatbqxy-823[wctav]\n" +
"froruixo-edvnhw-vwrudjh-829[rdhou]\n" +
"jvyyvzpcl-jhukf-aljouvsvnf-201[uwkic]\n" +
"nij-mywlyn-vumeyn-zchuhwcha-266[hnycm]\n" +
"ydjuhdqjyedqb-zubboruqd-tufbeocudj-244[vmkln]\n" +
"qlm-pbzobq-mixpqfz-doxpp-mrozexpfkd-575[zswni]\n" +
"qvbmzvibqwvit-moo-tijwzibwzg-330[ibvwz]\n" +
"pbeebfvir-fpniratre-uhag-freivprf-949[gvxlm]\n" +
"wfummczcyx-jfumncw-alumm-uwkocmcncih-890[vturj]\n" +
"dwbcjkun-npp-cajrwrwp-355[kstqo]\n" +
"dpssptjwf-cbtlfu-vtfs-uftujoh-441[ftsuj]\n" +
"vrurcjah-pajmn-npp-anbnjalq-303[tozvd]\n" +
"wfruflnsl-ojqqdgjfs-xfqjx-775[fjqls]\n" +
"pbafhzre-tenqr-qlr-qrirybczrag-897[yszub]\n" +
"sehheiylu-rkddo-udwyduuhydw-322[qbyad]\n" +
"upq-tfdsfu-cbtlfu-nbobhfnfou-103[vpxyh]\n" +
"ajvyjprwp-npp-dbna-cnbcrwp-901[stevo]\n" +
"bkzrrhehdc-bzmcx-bnzshmf-qdrdzqbg-833[msuya]\n" +
"amlqskcp-epybc-aylbw-rcaflmjmew-730[arbyn]\n" +
"wbhsfbohwcboz-dzoghwq-ufogg-gozsg-272[gobhw]\n" +
"ksodcbwnsr-dfcxsqhwzs-gqojsbusf-vibh-obozmgwg-194[rwimn]\n" +
"mfklstdw-usfvq-hmjuzskafy-424[ulgym]\n" +
"wfruflnsl-ojqqdgjfs-qfgtwfytwd-177[xbofz]\n" +
"sedikcuh-whqtu-isqludwuh-xkdj-jhqydydw-218[dhuqw]\n" +
"ltpedcxots-raphhxuxts-qphzti-advxhixrh-765[jahpi]\n" +
"zgmfyxypbmsq-djmucp-rcaflmjmew-548[aeoiv]\n" +
"qspkfdujmf-ezf-nbobhfnfou-207[lnkrt]\n" +
"fbebmtkr-zktwx-pxtihgbsxw-ietlmbv-zktll-kxlxtkva-943[hajmb]\n" +
"apwmeclga-hcjjwzcyl-bctcjmnkclr-548[yxnzl]\n" +
"rflsjynh-kqtbjw-btwpxmtu-177[tbjwf]\n" +
"kfg-jvtivk-treup-uvgcfpdvek-373[vkefg]\n" +
"upq-tfdsfu-kfmmzcfbo-nbobhfnfou-285[vsglz]\n" +
"chnylhuncihuf-mwupyhayl-bohn-xypyfijgyhn-266[pwahm]\n" +
"apwmeclga-zyqicr-dglylagle-886[lagce]\n" +
"jlidywncfy-xsy-qilembij-188[uxjts]\n" +
"jqwpihizlwca-lgm-lmaqov-954[laimq]\n" +
"qcffcgwjs-foppwh-gozsg-246[fgcop]\n" +
"bqxnfdmhb-rbzudmfdq-gtms-cdrhfm-287[dmbfh]\n" +
"gifavtkzcv-wcfnvi-rthlzjzkzfe-763[tmniq]\n" +
"uqtqbizg-ozilm-kivlg-kwibqvo-tijwzibwzg-720[qndzg]\n" +
"sxdobxkdsyxkv-mkxni-bomosfsxq-848[zyubw]\n" +
"qfmcusbwq-foppwh-kcfygvcd-662[cfpqw]\n" +
"sehheiylu-fbqijys-whqii-skijecuh-iuhlysu-660[kdjyq]\n" +
"sedikcuh-whqtu-uww-bqrehqjeho-660[dtawl]\n" +
"veqtekmrk-wgezirkiv-lyrx-eguymwmxmsr-464[emrkg]\n" +
"lqwhuqdwlrqdo-exqqb-uhdftxlvlwlrq-231[ydznk]\n" +
"sno-rdbqds-bzmcx-otqbgzrhmf-183[gomah]\n" +
"ujqgywfau-jsttal-hmjuzskafy-476[lghae]\n" +
"yrwxefpi-jpsaiv-gsrxemrqirx-100[yazxo]\n" +
"udglrdfwlyh-exqqb-sxufkdvlqj-569[dlqfu]\n" +
"ugjjgkanw-uzgugdslw-esjcwlafy-736[rnxjs]\n" +
"pdjqhwlf-sodvwlf-judvv-orjlvwlfv-673[vldfj]\n" +
"xekdwvwnzkqo-fahhuxawj-ajcejaanejc-524[ajewc]\n" +
"pwcvonofrcig-pibbm-fsqswjwbu-766[myazu]\n" +
"tcrjjzwzvu-wcfnvi-glityrjzex-893[bkuyx]\n" +
"lugjuacha-wbiwifuny-omyl-nymncha-448[mosph]\n" +
"ckgvutofkj-inuiurgzk-jkvgxzsktz-228[kguzi]\n" +
"ydjuhdqjyedqb-sqdto-ijehqwu-868[ozqsj]\n" +
"sxdobxkdsyxkv-zvkcdsm-qbkcc-myxdksxwoxd-640[xdksc]\n" +
"odkasqzuo-dmnnuf-dqmocgueufuaz-482[wfbke]\n" +
"wpuvcdng-tcddkv-wugt-vguvkpi-414[hayjs]\n" +
"lqwhuqdwlrqdo-edvnhw-uhfhlylqj-439[bjzye]\n" +
"wpuvcdng-dwppa-ceswkukvkqp-674[mxnkj]\n" +
"qzlozfhmf-bkzrrhehdc-okzrshb-fqzrr-zbpthrhshnm-365[hrzbf]\n" +
"raphhxuxts-rpcsn-rdpixcv-rjhidbtg-htgkxrt-635[yozvr]\n" +
"tfejldvi-xiruv-gcrjkzt-xirjj-tljkfdvi-jvimztv-321[veyxs]\n" +
"ryexqpqhteki-sxesebqju-iqbui-868[qebar]\n" +
"eqpuwogt-itcfg-hnqygt-tgegkxkpi-648[ywzjl]\n" +
"uzfqdzmfuazmx-pkq-bgdotmeuzs-482[zmudf]\n" +
"sbnqbhjoh-cbtlfu-bdrvjtjujpo-441[taquv]\n" +
"gokzyxsjon-bkwzkqsxq-lexxi-bomosfsxq-354[xoskq]\n" +
"oazegyqd-sdmpq-iqmbazulqp-dmnnuf-geqd-fqefuzs-456[qdefm]\n" +
"dwbcjkun-ljwmh-lxjcrwp-anbnjalq-875[hoynm]\n" +
"udskkaxawv-eadalsjq-yjsvw-xdgowj-klgjsyw-216[cnwyi]\n" +
"surmhfwloh-exqqb-sxufkdvlqj-439[tspmq]\n" +
"ksodcbwnsr-foppwh-zcuwghwqg-402[vopuk]\n" +
"zsxyfgqj-hmthtqfyj-fhvznxnynts-697[fhnty]\n" +
"yflexwxoalrp-yxphbq-bkdfkbbofkd-653[jzvpm]\n" +
"ltpedcxots-tvv-rdcipxcbtci-557[ctdip]\n" +
"slqryzjc-djmucp-qyjcq-756[cjqyd]\n" +
"rgndvtcxr-qphzti-bpcpvtbtci-817[tcpbi]\n" +
"ftzgxmbv-fbebmtkr-zktwx-vtgwr-vhtmbgz-lmhktzx-371[wzxvl]\n" +
"htqtwkzq-hfsid-yjhmstqtld-463[rxszy]\n" +
"rwcnawjcrxwju-yujbcrl-pajbb-mnenuxyvnwc-979[gkutb]\n" +
"gokzyxsjon-tovvilokx-kmaescsdsyx-562[dwlah]\n" +
"iutyaskx-mxgjk-lruckx-iayzuskx-ykxboik-826[kxiuy]\n" +
"vhglnfxk-zktwx-yehpxk-hixktmbhgl-891[diznt]\n" +
"sedikcuh-whqtu-kdijqrbu-sqdto-seqjydw-iuhlysui-790[lksjh]\n" +
"jyfvnlupj-zjhclunly-obua-vwlyhapvuz-617[pirsw]\n" +
"iuruxlar-sgmtkzoi-hgyqkz-zkinturume-670[qatsn]\n" +
"wkqxodsm-mrymyvkdo-mecdywob-cobfsmo-250[hgarm]\n" +
"odiih-kjbtnc-nwprwnnarwp-381[qpodn]\n" +
"kfg-jvtivk-tyftfcrkv-kirzezex-373[srcvd]\n" +
"gcfcnuls-aluxy-zotts-wuhxs-omyl-nymncha-552[clnsu]\n" +
"xmtjbzidx-zbb-xpnojhzm-nzmqdxz-421[mnkio]\n" +
"qjopwxha-acc-iwngapejc-160[jimst]\n" +
"emixwvqhml-kivlg-kwibqvo-aitma-564[qspyb]\n" +
"nvrgfezqvu-avccpsvre-cfxzjkztj-529[lmnsh]\n" +
"emixwvqhml-ktiaaqnqml-xtiabqk-oziaa-ikycqaqbqwv-746[ozadu]\n" +
"zhdsrqlchg-hjj-orjlvwlfv-751[hjlrv]\n" +
"cybyjqho-whqtu-uww-qsgkyiyjyed-478[szxuo]\n" +
"clxalrtyr-nsznzwlep-wzrtdetnd-405[lnrtz]\n" +
"sgmtkzoi-yigbktmkx-natz-rghuxgzuxe-722[gktxz]\n" +
"hjgbwuladw-tskcwl-sfsdqkak-502[txdsw]\n" +
"yrwxefpi-hci-vigimzmrk-646[hdmzy]\n" +
"hqcfqwydw-hqrryj-jusxdebewo-946[qwdeh]\n" +
"wsvsdkbi-qbkno-cmkfoxqob-rexd-yzobkdsyxc-276[wptxs]\n" +
"qfmcusbwq-qvcqczohs-zcuwghwqg-870[mnybx]\n" +
"clxalrtyr-nsznzwlep-cpdplcns-743[rtycz]\n" +
"fbebmtkr-zktwx-ktuubm-ybgtgvbgz-553[osmdy]\n" +
"jvuzbtly-nyhkl-yhtwhnpun-jovjvshal-ylzlhyjo-773[hlyjn]\n" +
"slqryzjc-aylbw-pcacgtgle-782[nxkri]\n" +
"tfcfiwlc-wcfnvi-wzeretzex-971[smobe]\n" +
"jef-iushuj-uww-qsgkyiyjyed-556[xzrwq]\n" +
"crwwv-yxphbq-xkxivpfp-653[pxvwb]\n" +
"hqcfqwydw-zubboruqd-husuylydw-244[lqeho]\n" +
"oxmeeuruqp-qss-eqdhuoqe-534[equos]\n" +
"qxdwpopgsdjh-rgndvtcxr-gpqqxi-gthtpgrw-687[gpdqr]\n" +
"mybbycsfo-mrymyvkdo-bocokbmr-692[pymza]\n" +
"myvybpev-oqq-yzobkdsyxc-250[sxytw]\n" +
"fnjyxwrinm-kdwwh-uxprbcrlb-329[natqu]\n" +
"aietsrmdih-nippcfier-gsrxemrqirx-958[iremp]\n" +
"xmrrq-tmffq-vwhdgqewfl-138[fqmrw]\n" +
"oqnidbshkd-bzmcx-sdbgmnknfx-599[nzdyx]\n" +
"eqttqukxg-ecpfa-eqcvkpi-ewuvqogt-ugtxkeg-128[mytkp]\n" +
"nchhg-ntwemz-amzdqkma-252[kmbop]\n" +
"bjfutsneji-jll-zxjw-yjxynsl-775[ndbsw]\n" +
"ktwbhtvmbox-lvtoxgzxk-angm-mxvaghehzr-319[ijqxb]\n" +
"kyelcrga-afmamjyrc-pcqcypaf-210[acyfm]\n" +
"myxcewob-qbkno-mkxni-oxqsxoobsxq-484[oxbqk]\n" +
"esyfwlau-vqw-kzahhafy-788[jikae]\n" +
"oqnidbshkd-eknvdq-btrsnldq-rdquhbd-391[njzml]\n" +
"qjopwxha-bhksan-opknwca-888[ahkno]\n" +
"udskkaxawv-jsttal-vwhdgqewfl-190[hqmnt]\n" +
"excdklvo-lexxi-crszzsxq-458[uavnl]\n" +
"frqvxphu-judgh-fdqgb-frdwlqj-wudlqlqj-179[bimaq]\n" +
"iuruxlar-kmm-ykxboiky-852[tijpz]\n" +
"tyepcyletzylw-mldvpe-lylwjdtd-509[lydet]\n" +
"frqvxphu-judgh-gbh-whfkqrorjb-101[mhbes]\n" +
"xqvwdeoh-edvnhw-zrunvkrs-699[zmudw]\n" +
"irdgrxzex-treup-fgvirkzfej-893[fbsyn]\n" +
"cxy-bnlanc-ljwmh-orwjwlrwp-771[ngpmz]\n" +
"eqpuwogt-itcfg-gii-ucngu-388[hzgae]\n" +
"ikhcxvmbex-cxeeruxtg-wxlbzg-553[mvnfs]\n" +
"mrxivrexmsrep-fyrrc-asvowlst-854[codsq]\n" +
"npmhcargjc-aylbw-qcptgacq-366[ditsg]\n" +
"ftzgxmbv-ietlmbv-zktll-phkdlahi-241[ltbhi]\n" +
"hqcfqwydw-tou-bewyijysi-270[hnvux]\n" +
"emixwvqhml-kivlg-abwziom-590[imlvw]\n" +
"pejji-nio-mecdywob-cobfsmo-926[wrjmp]\n" +
"bknsykmdsfo-oqq-dbksxsxq-640[naysz]\n" +
"gifavtkzcv-vxx-tfekrzedvek-789[cnwtp]\n" +
"kmjezxodgz-diozmivodjivg-agjrzm-xjiovdihzio-915[yqktj]\n" +
"shoewudys-vbemuh-qsgkyiyjyed-946[nqsjd]\n" +
"htqtwkzq-ojqqdgjfs-rfwpjynsl-749[hryqo]\n" +
"rmn-qcapcr-zyqicr-pcacgtgle-340[znstw]\n" +
"bnqqnrhud-bzmcx-bnmszhmldms-729[yfetv]\n" +
"surmhfwloh-gbh-rshudwlrqv-725[dsaym]\n" +
"jchipqat-tvv-itrwcdadvn-505[povhu]\n" +
"zgmfyxypbmsq-njyqrga-epyqq-rcaflmjmew-340[mqyae]\n" +
"froruixo-exqqb-pdunhwlqj-283[nmuqd]\n" +
"lnkfaypeha-xwogap-odellejc-784[ytrsz]\n" +
"jlidywncfy-xsy-fuvilunils-864[ilyfn]\n" +
"joufsobujpobm-dipdpmbuf-sftfbsdi-545[rwjnm]\n" +
"tvsnigxmpi-gerhc-gsexmrk-eguymwmxmsr-932[pivem]\n" +
"tfejldvi-xiruv-srjbvk-ivjvrity-815[vijrt]\n" +
"zuv-ykixkz-yigbktmkx-natz-zkinturume-410[kzitu]\n" +
"enzcntvat-pubpbyngr-qrcyblzrag-117[oywbs]\n" +
"wsvsdkbi-qbkno-lkcuod-nofovyzwoxd-744[xnuqc]\n" +
"wbhsfbohwcboz-foppwh-aobousasbh-246[nfsml]\n" +
"uiovmbqk-jcvvg-abwziom-720[nbqaz]\n" +
"etaqigpke-fag-fgrnqaogpv-674[gaefp]\n" +
"ejpanjwpekjwh-nwxxep-hkceopeyo-238[bmscu]\n" +
"qjopwxha-bhksan-wjwhuoeo-940[xenwh]\n" +
"etyyx-bzmcx-bnzshmf-qdzbpthrhshnm-729[hbmzn]\n" +
"uqtqbizg-ozilm-lgm-abwziom-356[tspmz]\n" +
"excdklvo-mybbycsfo-tovvilokx-psxkxmsxq-874[axwon]\n" +
"mvydjvxodqz-xviyt-xjvodib-pnzm-oznodib-187[nflym]\n" +
"ixccb-zhdsrqlchg-edvnhw-xvhu-whvwlqj-465[hcvwd]\n" +
"qspkfdujmf-votubcmf-tdbwfohfs-ivou-bdrvjtjujpo-181[esuzg]\n" +
"fkqbokxqflkxi-qlm-pbzobq-bdd-jxohbqfkd-601[dcgym]\n" +
"mtzslklcozfd-prr-nfdezxpc-dpcgtnp-301[tmnrk]\n" +
"xekdwvwnzkqo-lhwopey-cnwoo-wymqeoepekj-290[rzsnk]\n" +
"fubrjhqlf-sodvwlf-judvv-pdqdjhphqw-725[dfhjq]\n" +
"shoewudys-zubboruqd-skijecuh-iuhlysu-608[ushbd]\n" +
"zlkprjbo-doxab-zxkav-rpbo-qbpqfkd-679[bkopa]\n" +
"nzcczdtgp-mldvpe-opawzjxpye-587[tkbms]\n" +
"apuut-nxvqzibzm-cpio-yzkvmohzio-655[rsozd]\n" +
"rgllk-ngzzk-ymdwqfuzs-300[yhzxu]\n" +
"cvabijtm-jcvvg-uiviomumvb-538[ixajz]\n" +
"oazegyqd-sdmpq-otaoaxmfq-pqbmdfyqzf-248[qadfm]\n" +
"rtqlgevkng-fag-nqikuvkeu-960[nqdom]\n" +
"bnknqetk-cxd-cdrhfm-183[mfpwa]\n" +
"ohmnuvfy-wuhxs-wiuncha-lyuwkocmcncih-552[chunw]\n" +
"hqtyeqsjylu-jef-iushuj-tou-fkhsxqiydw-296[isfmy]\n" +
"kwtwznct-kwvacumz-ozilm-jiasmb-uiviomumvb-746[qmjyz]\n" +
"qfmcusbwq-foppwh-twbobqwbu-298[bwqfo]\n" +
"ykhknbqh-xqjju-owhao-472[hjtck]\n" +
"dszphfojd-tdbwfohfs-ivou-mbcpsbupsz-103[sbdfo]\n" +
"lahxpnwrl-ljwmh-nwprwnnarwp-641[srtpm]\n" +
"ckgvutofkj-lruckx-jkvruesktz-878[zjlyk]\n" +
"dyz-combod-zvkcdsm-qbkcc-nocsqx-926[yvute]\n" +
"ktwbhtvmbox-wrx-nlxk-mxlmbgz-345[lsuwt]\n" +
"nwilwcejc-nwxxep-zalhkuiajp-186[bznxr]\n" +
"uzfqdzmfuazmx-otaoaxmfq-bgdotmeuzs-846[mzafo]\n" +
"oxmeeuruqp-omzpk-oamfuzs-oazfmuzyqzf-352[ypdzg]\n" +
"zhdsrqlchg-fdqgb-ghsduwphqw-361[hdgqs]\n" +
"nchhg-jiasmb-amzdqkma-278[qklti]\n" +
"tfiifjzmv-upv-wzeretzex-295[itvos]\n" +
"eqttqukxg-ecpfa-ujkrrkpi-830[kepqr]\n" +
"clotzlnetgp-mldvpe-nzyeltyxpye-145[xfpsy]\n" +
"mbiyqoxsm-myvybpev-mkxni-mykdsxq-yzobkdsyxc-900[ymxbk]\n" +
"plolwdub-judgh-vfdyhqjhu-kxqw-vhuylfhv-621[zqwmy]\n" +
"atyzghrk-vxupkizork-jek-giwaoyozout-228[abrmv]\n" +
"zotts-xsy-mufym-162[mstyf]\n" +
"vhehkyne-ktuubm-mktbgbgz-293[qmytr]\n" +
"kwvacumz-ozilm-zijjqb-ivitgaqa-616[fkoxt]\n" +
"yaxsnlcrun-ajvyjprwp-snuuhknjw-anlnrerwp-771[zpyld]\n" +
"raphhxuxts-bpvctixr-eaphixr-vgphh-bpcpvtbtci-115[phtxb]\n" +
"nuatmlmdpage-odkasqzuo-qss-dqmocgueufuaz-768[umnqw]\n" +
"yknnkoera-lhwopey-cnwoo-nawymqeoepekj-680[eonkw]\n" +
"pybgmyargtc-aylbw-qyjcq-886[buzfp]\n" +
"gzefmnxq-ngzzk-iadwetab-638[zaegn]\n" +
"sbnqbhjoh-kfmmzcfbo-usbjojoh-129[acdkb]\n" +
"lxaaxbren-lujbbrornm-ljwmh-lxjcrwp-mnyjacvnwc-355[yzsuk]\n" +
"nchhg-lgm-nqvivkqvo-200[dystz]\n" +
"plolwdub-judgh-udeelw-rshudwlrqv-335[sihdt]\n" +
"wlsiayhcw-vumeyn-lymyulwb-292[zbrux]\n" +
"ytu-xjhwjy-hfsid-htfynsl-qtlnxynhx-411[adxmu]\n" +
"wkqxodsm-tovvilokx-ckvoc-822[uhgov]\n" +
"chnylhuncihuf-vumeyn-nluchcha-500[rcbmn]\n" +
"tfiifjzmv-lejkrscv-tyftfcrkv-jyzggzex-243[fjtvz]\n" +
"eqpuwogt-itcfg-tcddkv-tgugctej-310[pyemh]\n" +
"iuruxlar-xgsvgmotm-pkrrehkgt-xkykgxin-956[btwqp]\n" +
"shoewudys-sxesebqju-qdqboiyi-894[seqbd]\n" +
"zlkprjbo-doxab-gbiivybxk-pxibp-861[azyjx]\n" +
"ckgvutofkj-inuiurgzk-lotgtiotm-982[qszly]\n" +
"thnulapj-jshzzpmplk-jhukf-vwlyhapvuz-747[hpjlu]\n" +
"pybgmyargtc-hcjjwzcyl-qcptgacq-782[bxsuc]\n" +
"xgsvgmotm-vrgyzoi-mxgyy-iutzgotsktz-150[gtmoy]\n" +
"laffe-yigbktmkx-natz-jkyomt-696[ktafm]\n" +
"zvyvgnel-tenqr-pubpbyngr-znexrgvat-507[wfjhu]\n" +
"pelbtravp-pnaql-znantrzrag-403[cbyja]\n" +
"jqwpihizlwca-akidmvomz-pcvb-apqxxqvo-850[oxymv]\n" +
"cvabijtm-ntwemz-twoqabqka-954[atbmq]\n" +
"zixppfcfba-avb-zlkqxfkjbkq-809[zlmjc]\n" +
"sebehvkb-zubboruqd-tufqhjcudj-556[budeh]\n" +
"lqwhuqdwlrqdo-fdqgb-ghvljq-621[qdlgh]\n" +
"qlm-pbzobq-crwwv-zxkav-zlxqfkd-rpbo-qbpqfkd-731[ciyxw]\n" +
"pwcvonofrcig-gqojsbusf-vibh-qighcasf-gsfjwqs-740[csebm]\n" +
"mvydjvxodqz-kmjezxodgz-kgvnodx-bmvnn-yzqzgjkhzio-239[zdovg]\n" +
"kzgwomvqk-xtiabqk-oziaa-tijwzibwzg-564[menyj]\n" +
"ksodcbwnsr-xszzmpsob-kcfygvcd-454[mbaod]\n" +
"ejpanjwpekjwh-xwogap-hwxknwpknu-472[wpjkn]\n" +
"mvydjvxodqz-hvbizodx-wpiit-hvivbzhzio-967[ivzdh]\n" +
"mvydjvxodqz-mvwwdo-nzmqdxzn-681[jryzk]\n" +
"enqvbnpgvir-rtt-freivprf-871[lgqrc]\n" +
"hvbizodx-wpiit-kpmxcvndib-291[dyjmn]\n" +
"molgbzqfib-mixpqfz-doxpp-xkxivpfp-965[pxfib]\n" +
"fbebmtkr-zktwx-cxeeruxtg-nlxk-mxlmbgz-137[dckut]\n" +
"luxciuwncpy-luvvcn-mbcjjcha-500[qsvzt]\n" +
"apwmeclga-hcjjwzcyl-qyjcq-704[cjalq]\n" +
"wpuvcdng-eqttqukxg-uecxgpigt-jwpv-cpcnauku-830[ucgpt]\n" +
"iehepwnu-cnwza-fahhuxawj-pnwejejc-940[ewahj]\n" +
"pbybeshy-pbeebfvir-pnaql-pbngvat-freivprf-715[uyzwp]\n" +
"htsxzrjw-lwfij-ojqqdgjfs-zxjw-yjxynsl-957[iyonc]\n" +
"sxdobxkdsyxkv-wsvsdkbi-qbkno-zvkcdsm-qbkcc-bomosfsxq-536[mbyan]\n" +
"fruurvlyh-fkrfrodwh-uhdftxlvlwlrq-335[rflhu]\n" +
"froruixo-hjj-orjlvwlfv-387[uyawn]\n" +
"myvybpev-lexxi-vklybkdybi-978[ybvei]\n" +
"chnylhuncihuf-vohhs-xymcah-240[yxnmh]\n" +
"tagzsrsjvgmk-vqw-vwhsjlewfl-606[svwgj]\n" +
"zbytomdsvo-lexxi-domrxyvyqi-250[oxydi]\n" +
"qfkkj-clmmte-opgpwzaxpye-821[pekma]\n" +
"lgh-kwujwl-udskkaxawv-jsttal-hmjuzskafy-320[axyrm]\n" +
"irdgrxzex-nvrgfezqvu-avccpsvre-cfxzjkztj-191[sclzh]\n" +
"mhi-lxvkxm-xzz-etuhktmhkr-319[rcomn]\n" +
"lhkhszqx-fqzcd-dff-sdbgmnknfx-391[ugevx]\n" +
"apwmeclga-aylbw-ylyjwqgq-314[izfye]\n" +
"yflexwxoalrp-zlkprjbo-doxab-ciltbo-qbzeklildv-341[byclp]\n" +
"cvabijtm-kwzzwaqdm-ntwemz-abwziom-252[rdmvn]\n" +
"qfkkj-upwwjmply-epnsyzwzrj-899[okhgz]\n" +
"jxdkbqfz-avb-zlkqxfkjbkq-861[wptxb]\n" +
"gpsxdprixkt-qphzti-hwxeexcv-947[krgwe]\n" +
"nij-mywlyn-wuhxs-wiuncha-lymyulwb-968[wylnu]\n" +
"sbnqbhjoh-kfmmzcfbo-ufdiopmphz-987[bfhmo]\n" +
"guahyncw-jfumncw-alumm-xyjfisgyhn-500[htamn]\n" +
"ytu-xjhwjy-jll-ijxnls-879[duthg]\n" +
"lgh-kwujwl-usfvq-ugslafy-esfsywewfl-944[ilszy]\n" +
"tvsnigxmpi-tpewxmg-kveww-xiglrspskc-152[gipsw]\n" +
"joufsobujpobm-cbtlfu-dvtupnfs-tfswjdf-129[fubjo]\n" +
"rwcnawjcrxwju-bljenwpna-qdwc-mnyuxhvnwc-225[wncja]\n" +
"qzchnzbshud-okzrshb-fqzrr-rzkdr-989[rzhbd]\n" +
"qzoggwtwsr-pogysh-rsjszcdasbh-896[sghor]\n" +
"gzefmnxq-dmnnuf-xmnadmfadk-326[tvuiw]\n" +
"qzoggwtwsr-pibbm-zopcfohcfm-792[jsmfu]\n" +
"mvydjvxodqz-xviyt-xjvodib-hvivbzhzio-369[iceny]\n" +
"wkqxodsm-lkcuod-cdybkqo-224[dkocq]\n" +
"veqtekmrk-ikk-wxsveki-542[keivm]\n" +
"zlkprjbo-doxab-yxphbq-pqloxdb-419[ckdtm]\n" +
"buzahisl-ibuuf-klzpnu-721[stjnm]\n" +
"hwdtljsnh-kqtbjw-ijajqturjsy-515[plnqy]\n" +
"luxciuwncpy-jfumncw-alumm-lyuwkocmcncih-474[lqpco]\n" +
"tinnm-ibghopzs-rms-aobousasbh-506[sboah]\n" +
"pbeebfvir-rtt-ratvarrevat-403[tdokj]\n" +
"dmybmsuzs-pkq-efadmsq-300[msdqa]\n" +
"ujqgywfau-tmffq-dgyaklauk-970[yxmid]\n" +
"ovbunmneqbhf-enoovg-hfre-grfgvat-481[efgno]\n" +
"hqfxxnknji-kzeed-uqfxynh-lwfxx-wjhjnansl-957[nxfhj]\n" +
"plolwdub-judgh-edvnhw-pdqdjhphqw-985[dsxhg]\n" +
"nwlddtqtpo-awldetn-rcldd-nfdezxpc-dpcgtnp-353[dnptc]\n" +
"bwx-amkzmb-xzwrmkbqtm-ntwemz-amzdqkma-668[swmnl]\n" +
"bqxnfdmhb-qzaahs-rdquhbdr-443[bdhqa]\n" +
"egdytrixat-ide-htrgti-uadltg-steadnbtci-297[zampy]\n" +
"gsrwyqiv-kvehi-gerhc-gsexmrk-erepcwmw-880[bkwts]\n" +
"nsyjwsfyntsfq-gfxpjy-jslnsjjwnsl-749[lvzus]\n" +
"dfcxsqhwzs-pibbm-gvwddwbu-246[dqbem]\n" +
"mtzslklcozfd-ojp-fdpc-epdetyr-613[dpcef]\n" +
"gbc-frperg-ohaal-erfrnepu-351[reafg]\n" +
"gvaaz-cbtlfu-efqbsunfou-311[dvnmz]\n" +
"ugdgjxmd-tskcwl-umklgewj-kwjnauw-892[wgjku]\n" +
"iruzfrtkzmv-avccpsvre-nfibjyfg-243[jzoyc]\n" +
"shoewudys-hqrryj-bqrehqjeho-296[heqrj]\n" +
"hwdtljsnh-kqtbjw-htsyfnsrjsy-827[dntpc]\n" +
"zilqwikbqdm-kivlg-uiviomumvb-902[imvbk]\n" +
"rsvxltspi-sfnigx-wxsveki-984[sixve]\n" +
"surmhfwloh-gbh-xvhu-whvwlqj-387[hwluv]\n" +
"ubhatstkwhnl-yehpxk-wxlbzg-137[raqjb]\n" +
"oknkvcta-itcfg-uecxgpigt-jwpv-ocpcigogpv-596[cgpio]\n" +
"amjmpdsj-djmucp-nspafyqgle-470[ztpqn]\n" +
"zixppfcfba-avb-abpfdk-471[abfpc]\n" +
"owshgfarwv-jsttal-vwkayf-944[smcyx]\n" +
"vjpwncrl-ljwmh-lxjcrwp-lxwcjrwvnwc-589[irbxq]\n" +
"qvbmzvibqwvit-ziuxioqvo-lgm-amzdqkma-928[hgfln]\n" +
"lxuxaodu-kjbtnc-jwjuhbrb-147[bjuxa]\n" +
"etaqigpke-fag-yqtmujqr-440[qaegt]\n" +
"zekvierkzferc-irdgrxzex-jtrmvexvi-ylek-rthlzjzkzfe-633[gkyzp]\n" +
"mfklstdw-hdsklau-yjskk-kwjnauwk-762[vnfzg]\n" +
"pkl-oaynap-fahhuxawj-oanreyao-706[mdfpn]\n" +
"hwdtljsnh-hmthtqfyj-rfsfljrjsy-359[sxziu]\n" +
"fab-eqodqf-ngzzk-bgdotmeuzs-144[kxags]\n" +
"tagzsrsjvgmk-tskcwl-vwhsjlewfl-424[ejuah]\n" +
"kzgwomvqk-jiasmb-uizsmbqvo-590[mbiko]\n" +
"qjopwxha-xqjju-oanreyao-758[ubmon]\n" +
"hvbizodx-xmtjbzidx-nxvqzibzm-cpio-yzkgjthzio-889[rmyqo]\n" +
"iuruxlar-kmm-jkvruesktz-644[kruma]\n" +
"ujqgywfau-jsttal-vwhdgqewfl-710[hbdlx]\n" +
"jlidywncfy-wuhxs-wiuncha-yhachyylcha-630[hycaw]\n" +
"lugjuacha-wlsiayhcw-dyffsvyuh-uhufsmcm-890[juefh]\n" +
"hjgbwuladw-xdgowj-hmjuzskafy-398[wqigl]\n" +
"yuxufmdk-sdmpq-pkq-etubbuzs-456[wldkg]\n" +
"vcibutulxiom-dyffsvyuh-qilembij-110[jdnmz]\n" +
"nzwzcqfw-clmmte-dpcgtnpd-509[cdmnp]\n" +
"aczupnetwp-nlyoj-nzletyr-zapcletzyd-665[zelnp]\n" +
"htsxzrjw-lwfij-wfintfhynaj-kqtbjw-knsfshnsl-983[kytzm]\n" +
"enqvbnpgvir-onfxrg-qrirybczrag-611[rgnbi]\n" +
"molgbzqfib-ciltbo-xkxivpfp-159[biflo]\n" +
"plolwdub-judgh-fkrfrodwh-ghyhorsphqw-517[hdorw]\n" +
"gzefmnxq-omzpk-oazfmuzyqzf-872[zkycu]\n" +
"qjopwxha-lhwopey-cnwoo-naoawnyd-186[cvyno]\n" +
"jyfvnlupj-ipvohghykvbz-jovjvshal-ylzlhyjo-435[xlenk]\n" +
"ajmrxjlcren-kjbtnc-jwjuhbrb-329[klcuz]\n" +
"wdjcvuvmyjpn-ezggtwzvi-jkzmvodjin-603[gmveh]\n" +
"muqfedyput-fbqijys-whqii-bqrehqjeho-192[vdlge]\n" +
"ktfitzbgz-xzz-ftgtzxfxgm-605[izfql]\n" +
"bknsykmdsfo-oqq-wkbuodsxq-458[stifb]\n" +
"slqryzjc-hcjjwzcyl-yaosgqgrgml-314[qymir]\n" +
"gpewwmjmih-veffmx-xvemrmrk-126[itcvu]\n" +
"rdadguja-gpqqxi-ldgzhwde-297[hnvso]\n" +
"lxaaxbren-mhn-cnlqwxuxph-251[xvjuz]\n" +
"xst-wigvix-fewoix-gsrxemrqirx-698[xireg]\n" +
"iehepwnu-cnwza-zua-wymqeoepekj-108[sdnmj]\n" +
"oknkvcta-itcfg-rncuvke-itcuu-hkpcpekpi-908[pgfbe]\n"+
"enqvbnpgvir-ohaal-hfre-grfgvat-351[hsgdf]\n" +
"ixccb-iorzhu-hqjlqhhulqj-647[hqcij]\n" +
"apuut-agjrzm-jkzmvodjin-915[jamuz]\n" +
"hqcfqwydw-rqiauj-ijehqwu-530[qwhij]\n" +
"vhehkyne-ktwbhtvmbox-lvtoxgzxk-angm-kxvxbobgz-683[tsurp]\n" +
"gntmfefwitzx-idj-knsfshnsl-723[fnsit]\n" +
"ajvyjprwp-bljenwpna-qdwc-ujkxajcxah-563[yskxv]\n" +
"joufsobujpobm-dboez-dpbujoh-mbcpsbupsz-259[bopuj]\n" +
"xlrypetn-prr-nzyeltyxpye-847[yeprl]\n" +
"zuv-ykixkz-xgsvgmotm-lruckx-jkvgxzsktz-696[ijlfz]\n" +
"jqwpihizlwca-moo-lmxtwgumvb-798[nkzsr]\n" +
"jsvagsulanw-kusnwfywj-zmfl-klgjsyw-736[ectrq]\n" +
"ykhknbqh-nwxxep-nawymqeoepekj-758[cfvdy]\n" +
"kzeed-gfxpjy-tujwfyntsx-385[aunmy]\n" +
"slqryzjc-qaytclecp-fslr-dglylagle-184[lcyae]\n" +
"laffe-vrgyzoi-mxgyy-iutzgotsktz-410[gtyzf]\n" +
"gpbepvxcv-hrpktcvtg-wjci-stktadebtci-141[zoqhx]\n" +
"yaxsnlcrun-lqxlxujcn-mnyuxhvnwc-641[nxclu]\n" +
"tagzsrsjvgmk-kusnwfywj-zmfl-dstgjslgjq-294[gayon]\n" +
"kwzzwaqdm-zijjqb-xczkpiaqvo-902[mkgjt]\n" +
"mfklstdw-usfvq-ugslafy-xafsfuafy-684[fsaul]\n" +
"zvyvgnel-tenqr-ovbunmneqbhf-sybjre-fgbentr-117[shfce]\n" +
"emixwvqhml-akidmvomz-pcvb-amzdqkma-720[relbk]\n" +
"rdggdhxkt-eaphixr-vgphh-hwxeexcv-973[xozyv]\n" +
"bqvvu-zua-iwngapejc-992[nmdax]\n" +
"bjfutsneji-kqtbjw-wjxjfwhm-203[irjmx]\n" +
"bdavqofuxq-nmewqf-abqdmfuaze-976[vgzhc]\n" +
"vdzonmhydc-okzrshb-fqzrr-rzkdr-313[rzdhk]\n" +
"sawlkjevaz-oywrajcan-dqjp-wjwhuoeo-836[ajwoe]\n" +
"fruurvlyh-gbh-sxufkdvlqj-413[kftmo]\n" +
"fruurvlyh-sodvwlf-judvv-ghsorbphqw-569[tadzk]\n" +
"sbejpbdujwf-tdbwfohfs-ivou-dpoubjonfou-103[rbqio]\n" +
"oxmeeuruqp-otaoaxmfq-xasuefuoe-222[ozipy]\n" +
"rdggdhxkt-qphzti-ejgrwphxcv-921[tusrb]\n" +
"dkqjcbctfqwu-fag-yqtmujqr-882[kzvuf]\n" +
"gzefmnxq-dmnnuf-mzmxkeue-248[menfu]\n" +
"kgjgrypw-epybc-aylbw-kylyeckclr-314[mlvhs]\n" +
"bwx-amkzmb-akidmvomz-pcvb-abwziom-148[nmtyw]\n" +
"ckgvutofkj-sorozgxe-mxgjk-xghhoz-xkykgxin-670[gkxoh]\n" +
"zhdsrqlchg-fkrfrodwh-ghsorbphqw-803[cjybd]\n" +
"hvbizodx-wvnfzo-adivixdib-603[xwstz]\n" +
"tvsnigxmpi-gerhc-hitpscqirx-204[icghp]\n" +
"jrncbavmrq-cynfgvp-tenff-npdhvfvgvba-741[ybszn]\n" +
"mbiyqoxsm-pvygob-psxkxmsxq-952[mjfnc]\n" +
"gsrwyqiv-kvehi-veffmx-gywxsqiv-wivzmgi-282[bdrgj]\n" +
"clxalrtyr-xtwtelcj-rclop-awldetn-rcldd-cpdplcns-847[lcdrt]\n" +
"ahngzyzqcntr-bzmcx-sdbgmnknfx-287[fmyqt]\n" +
"zgmfyxypbmsq-aylbw-amyrgle-bctcjmnkclr-340[mybcl]\n" +
"fydelmwp-prr-nzyeltyxpye-717[gfjxa]\n" +
"rnqnyfwd-lwfij-rflsjynh-wfggny-xfqjx-931[fnjwy]\n" +
"zilqwikbqdm-xtiabqk-oziaa-twoqabqka-278[ftonr]\n" +
"bjfutsneji-gzssd-uzwhmfxnsl-827[sfjnu]\n" +
"ojk-nzxmzo-pinovwgz-agjrzm-jkzmvodjin-733[zjomn]\n" +
"ygcrqpkbgf-dcumgv-fgukip-570[vmhxn]\n" +
"dzczkrip-xiruv-srjbvk-jyzggzex-945[uzneh]\n" +
"bkzrrhehdc-bzmcx-lzmzfdldms-287[eclvd]\n" +
"ziuxioqvo-kpwkwtibm-lmxizbumvb-564[txsru]\n" +
"kzgwomvqk-lgm-lmxizbumvb-122[mbgkl]\n" +
"htsxzrjw-lwfij-idj-xjwanhjx-463[obdze]\n" +
"gntmfefwitzx-kqtbjw-wjxjfwhm-749[qzutv]\n" +
"htsxzrjw-lwfij-jll-tujwfyntsx-671[xugan]\n" +
"ymszqfuo-rxaiqd-etubbuzs-118[ubqsz]\n" +
"vdzonmhydc-azrjds-lzqjdshmf-989[dzhjm]\n" +
"dyz-combod-bkllsd-oxqsxoobsxq-354[nrmkx]\n" +
"pyknyegle-afmamjyrc-yaosgqgrgml-626[zdlfg]\n" +
"oxmeeuruqp-vqxxknqmz-oazfmuzyqzf-352[rnsyt]\n" +
"qjopwxha-xqjju-pnwejejc-654[jepqw]\n" +
"wifilzof-jfumncw-alumm-xypyfijgyhn-604[fjerw]\n" +
"vagreangvbany-enoovg-fuvccvat-533[gncot]\n" +
"avw-zljyla-zjhclunly-obua-thuhnltlua-669[wathd]\n" +
"ynssr-lvtoxgzxk-angm-mxvaghehzr-345[vopnm]\n" +
"cvabijtm-uqtqbizg-ozilm-xtiabqk-oziaa-lmdmtwxumvb-928[imabt]\n" +
"frqvxphu-judgh-sodvwlf-judvv-pdqdjhphqw-751[azovy]\n" +
"qmpmxevc-kvehi-jyddc-fyrrc-qerekiqirx-282[ygmhv]\n" +
"fodvvlilhg-udeelw-pdunhwlqj-153[sndmo]\n" +
"gpsxdprixkt-ytaanqtpc-gthtpgrw-765[tpgar]\n" +
"cvabijtm-kpwkwtibm-bmkpvwtwog-174[wbkmt]\n" +
"vetllbybxw-yehpxk-wxlbzg-891[yekxl]\n" +
"nzwzcqfw-nlyoj-dezclrp-275[zclnw]\n" +
"qmpmxevc-kvehi-glsgspexi-gsrxemrqirx-828[exgim]\n" +
"xtwtelcj-rclop-dnlgpyrpc-sfye-hzcvdsza-873[xmpon]\n" +
"jrncbavmrq-pnaql-jbexfubc-793[bacjn]\n" +
"ohmnuvfy-yaa-lymyulwb-266[yalmu]\n" +
"nzwzcqfw-aczupnetwp-awldetn-rcldd-pyrtyppctyr-613[pctwd]\n" +
"vqr-ugetgv-uecxgpigt-jwpv-rwtejcukpi-752[geptu]\n" +
"tfcfiwlc-lejkrscv-upv-rthlzjzkzfe-607[tcfns]\n" +
"hwdtljsnh-uqfxynh-lwfxx-knsfshnsl-229[xtngb]\n" +
"iuruxlar-igtje-iayzuskx-ykxboik-930[kmghr]\n" +
"xjgjmapg-ezggtwzvi-hvivbzhzio-421[gzivh]\n" +
"gpbepvxcv-hrpktcvtg-wjci-hwxeexcv-349[xswrp]\n" +
"tcorcikpi-eqttqukxg-gii-hkpcpekpi-622[ruxyk]\n" +
"ygcrqpkbgf-ejqeqncvg-ucngu-440[gcqen]\n" +
"etyyx-dff-qdbdhuhmf-729[wskto]\n" +
"tfiifjzmv-upv-vexzevvizex-399[veizf]\n" +
"houngfgxjuay-sorozgxe-mxgjk-jek-aykx-zkyzotm-566[aimhd]\n" +
"hcd-gsqfsh-dzoghwq-ufogg-aobousasbh-714[ynfie]\n" +
"foadouwbu-qobrm-qcohwbu-zopcfohcfm-792[obcfu]\n" +
"ynukcajey-oywrajcan-dqjp-wjwhuoeo-680[jaowy]\n" +
"rflsjynh-jll-rfsfljrjsy-489[jlfrs]\n" +
"vkrhzxgbv-pxtihgbsxw-yehpxk-mktbgbgz-917[igtvy]\n" +
"hjgbwuladw-tskcwl-dgyaklauk-294[aklwd]\n" +
"cvabijtm-jcvvg-zmikycqaqbqwv-772[vcqab]\n" +
"odiih-yujbcrl-pajbb-vjwjpnvnwc-849[jbcin]\n" +
"tinnm-tzcksf-igsf-hsghwbu-220[bnamt]\n" +
"pbeebfvir-wryylorna-jbexfubc-637[egouk]\n" +
"xmtjbzidx-xviyt-yzqzgjkhzio-265[vxsry]\n" +
"avw-zljyla-zjhclunly-obua-klwhyatlua-201[sjayl]\n" +
"dfcxsqhwzs-qvcqczohs-fsgsofqv-246[dosrp]\n" +
"rzvkjiduzy-xviyt-xjvodib-kpmxcvndib-291[cwzla]\n" +
"gcfcnuls-aluxy-mwupyhayl-bohn-wihnuchgyhn-968[hnuyc]\n" +
"dyz-combod-lsyrkjkbnyec-bkllsd-domrxyvyqi-328[vtxzd]\n" +
"fruurvlyh-mhoobehdq-dftxlvlwlrq-907[jlves]\n" +
"mrxivrexmsrep-gerhc-gsexmrk-tyvglewmrk-152[wzuly]\n" +
"votubcmf-gmpxfs-pqfsbujpot-883[fpbmo]\n" +
"bljenwpna-qdwc-anbnjalq-329[lcwmy]\n" +
"xekdwvwnzkqo-ydkykhwpa-wjwhuoeo-550[toavy]\n" +
"yhkpvhjapcl-yhiipa-jbzavtly-zlycpjl-201[lpyah]\n" +
"xjinphzm-bmvyz-wvnfzo-nzmqdxzn-681[ykfxe]\n" +
"pbeebfvir-rtt-ybtvfgvpf-507[bftve]\n" +
"gvcskirmg-ikk-hizipstqirx-750[iyquj]\n" +
"yhwooebeaz-lhwopey-cnwoo-oanreyao-108[tmuag]\n" +
"wlqqp-jtrmvexvi-ylek-nfibjyfg-581[tnrhf]\n" +
"tfiifjzmv-avccpsvre-jyzggzex-477[mvnjr]\n" +
"xjmmjndqz-zbb-yzndbi-811[bzdjm]\n" +
"qjopwxha-xwogap-nayaerejc-160[isjqz]\n" +
"qzlozfhmf-azrjds-knfhrshbr-573[dfmys]\n" +
"vhglnfxk-zktwx-vetllbybxw-vtgwr-vhtmbgz-ybgtgvbgz-761[gbtvl]\n" +
"etaqigpke-ecpfa-eqcvkpi-cpcnauku-336[eyxtb]\n" +
"lqwhuqdwlrqdo-fdqgb-frdwlqj-zrunvkrs-933[tvijl]\n" +
"gvcskirmg-tvsnigxmpi-gerhc-gsexmrk-wlmttmrk-828[szawg]\n" +
"irdgrxzex-kfg-jvtivk-wcfnvi-jyzggzex-269[givxz]\n" +
"cqwdujys-sqdto-iqbui-270[siyeh]\n" +
"bnqqnrhud-bgnbnkzsd-trdq-sdrshmf-807[dnbqr]\n" +
"rgndvtcxr-hrpktcvtg-wjci-prfjxhxixdc-193[yjsht]\n" +
"qekrixmg-hci-xvemrmrk-282[mreik]\n" +
"xcitgcpixdcpa-snt-apqdgpidgn-349[mfywv]\n" +
"wkqxodsm-pvygob-wkbuodsxq-978[ysamp]\n" +
"aoubshwq-qvcqczohs-kcfygvcd-558[ytvls]\n" +
"tyepcyletzylw-qwzhpc-opalcexpye-301[gamdn]\n" +
"tfcfiwlc-treup-uvjzxe-607[nrthm]\n" +
"ubhatstkwhnl-lvtoxgzxk-angm-inkvatlbgz-865[tagkl]\n" +
"wihmogyl-aluxy-yaa-qilembij-890[emvct]\n" +
"bxaxipgn-vgpst-ltpedcxots-gpqqxi-hidgpvt-245[pgtxi]\n" +
"jfifqxov-doxab-mixpqfz-doxpp-obpbxoze-107[ghpyi]\n" +
"gvaaz-dpssptjwf-sbccju-fohjoffsjoh-675[pfzwa]\n" +
"gzefmnxq-eomhqzsqd-tgzf-efadmsq-378[qefmz]\n" +
"emixwvqhml-kivlg-zmkmqdqvo-876[dcfin]\n" +
"fodvvlilhg-fdqgb-frqwdlqphqw-725[qdflg]\n" +
"laffe-pkrrehkgt-rumoyzoiy-670[dyjut]\n" +
"egdytrixat-qphzti-tcvxcttgxcv-245[tcxgi]\n" +
"htqtwkzq-wfintfhynaj-xhfajsljw-mzsy-jslnsjjwnsl-645[eynzi]\n" +
"vrurcjah-pajmn-npp-mnyuxhvnwc-563[npach]\n" +
"ejpanjwpekjwh-acc-klanwpekjo-576[jaekp]\n" +
"kwvacumz-ozilm-kpwkwtibm-uizsmbqvo-876[mikwz]\n" +
"hjgbwuladw-xdgowj-esfsywewfl-866[byzdm]\n" +
"pbybeshy-wryylorna-npdhvfvgvba-351[stmxy]\n" +
"qjopwxha-ywjzu-hkceopeyo-654[tysoa]\n" +
"lhkhszqx-fqzcd-dff-vnqjrgno-417[fqdhn]\n" +
"rgllk-otaoaxmfq-fdmuzuzs-768[vkqac]\n" +
"ohmnuvfy-xsy-omyl-nymncha-214[hmtfs]\n" +
"enzcntvat-cynfgvp-tenff-nanylfvf-455[cuimh]\n" +
"sedikcuh-whqtu-sehheiylu-tou-bqrehqjeho-868[ydaux]\n" +
"tyepcyletzylw-ojp-opalcexpye-145[wciks]\n" +
"udpsdjlqj-hjj-frqwdlqphqw-309[gbpcz]\n" +
"eqpuwogt-itcfg-lgnnadgcp-vtckpkpi-388[gpcti]\n" +
"rkpqxyib-pzxsbkdbo-erkq-zrpqljbo-pbosfzb-133[bpkoq]\n" +
"kdijqrbu-sxesebqju-tufqhjcudj-114[tdbva]\n" +
"gsvvswmzi-wgezirkiv-lyrx-irkmriivmrk-412[twsrk]\n" +
"ucynmlgxcb-qaytclecp-fslr-amlryglkclr-704[lcrya]\n" +
"xst-wigvix-veffmx-wxsveki-100[ocvmr]\n" +
"surmhfwloh-vfdyhqjhu-kxqw-frqwdlqphqw-829[hqwfd]\n" +
"xmrrq-usfvq-esfsywewfl-528[alidm]\n" +
"zhdsrqlchg-lqwhuqdwlrqdo-sodvwlf-judvv-ghsorbphqw-777[rtnmj]\n" +
"egdytrixat-xcitgcpixdcpa-rwdrdapit-uxcpcrxcv-245[cdabn]\n" +
"yrwxefpi-ikk-gywxsqiv-wivzmgi-152[iwgkv]\n" +
"qcffcgwjs-foppwh-obozmgwg-558[zotsu]\n" +
"veqtekmrk-gerhc-gsexmrk-hitpscqirx-568[nczdq]\n" +
"gzefmnxq-pkq-pqbmdfyqzf-794[jxrmh]\n" +
"eadalsjq-yjsvw-usfvq-ugslafy-ugflsafewfl-632[fsalu]\n" +
"esyfwlau-usfvq-ugslafy-vwhdgqewfl-684[flsuw]\n" +
"ktfitzbgz-fbebmtkr-zktwx-utldxm-wxlbzg-683[afwhg]\n" +
"wihmogyl-aluxy-vohhs-uwkocmcncih-292[wzryd]\n" +
"bkzrrhehdc-idkkxadzm-lzmzfdldms-677[oxwvn]\n" +
"clxalrtyr-qwzhpc-lnbftdtetzy-249[zryvn]\n" +
"rgllk-fab-eqodqf-vqxxknqmz-pqbxakyqzf-222[qfkxa]\n" +
"xjinphzm-bmvyz-xviyt-mzxzdqdib-603[xnhfs]\n" +
"htsxzrjw-lwfij-hmthtqfyj-wjfhvznxnynts-385[zreuy]\n" +
"myvybpev-gokzyxsjon-oqq-nozvyiwoxd-692[iyzuj]\n" +
"hcd-gsqfsh-pogysh-gvwddwbu-480[mysuk]\n" +
"hcd-gsqfsh-foppwh-rsgwub-428[kvtfs]\n" +
"frqvxphu-judgh-exqqb-uhvhdufk-621[wtgmn]\n" +
"vhglnfxk-zktwx-vahvhetmx-vhgmtbgfxgm-345[hnamj]\n" +
"tagzsrsjvgmk-usfvq-ugslafy-ugflsafewfl-892[yckbv]\n" +
"joufsobujpobm-gmpxfs-vtfs-uftujoh-233[foujs]\n" +
"zsxyfgqj-ojqqdgjfs-zxjw-yjxynsl-593[jqsxy]\n" +
"bnknqetk-atmmx-qdzbpthrhshnm-131[ecnmt]\n" +
"hmsdqmzshnmzk-dff-sqzhmhmf-859[dnxcz]\n" +
"hqtyeqsjylu-tou-udwyduuhydw-348[uydhq]\n" +
"ktiaaqnqml-kpwkwtibm-zmikycqaqbqwv-772[tlrsg]\n" +
"nzydfxpc-rclop-mtzslklcozfd-mfyyj-nfdezxpc-dpcgtnp-951[cpdfz]\n" +
"ckgvutofkj-hatte-gtgreyoy-644[tgeko]\n" +
"iwcjapey-zua-paydjkhkcu-628[hntmg]\n" +
"bnknqetk-okzrshb-fqzrr-trdq-sdrshmf-729[tuzoy]\n" +
"qmpmxevc-kvehi-yrwxefpi-glsgspexi-wlmttmrk-828[hsyvf]\n" +
"amjmpdsj-njyqrga-epyqq-qcptgacq-106[bhysd]\n" +
"dwbcjkun-ljwmh-mnyuxhvnwc-641[wuyrz]\n" +
"gspsvjyp-jpsaiv-hiwmkr-854[zthel]\n" +
"gsrwyqiv-kvehi-gerhc-stivexmsrw-750[whgse]\n" +
"xjgjmapg-wpiit-ozxcijgjbt-889[ytsop]\n" +
"xgjougizobk-kmm-rghuxgzuxe-280[cwrty]\n" +
"zovldbkfz-oxjmxdfkd-oxyyfq-ixyloxqlov-653[snkwb]\n" +
"qczcftiz-qvcqczohs-gsfjwqsg-142[cqszf]\n" +
"krxqjijamxdb-mhn-ldbcxvna-bnaerln-771[ravbt]\n" +
"pybgmyargtc-bwc-bcqgel-860[bcgya]\n" +
"wyvqljapsl-jovjvshal-shivyhavyf-773[vahjl]\n" +
"pbafhzre-tenqr-onfxrg-bcrengvbaf-221[zyaro]\n" +
"glrcplyrgmlyj-bwc-pcqcypaf-132[clpyg]\n" +
"dpmpsgvm-dboez-dpbujoh-tfswjdft-545[bdmzf]\n" +
"dkqjcbctfqwu-rncuvke-itcuu-cpcnauku-700[cuknq]\n" +
"ajmrxjlcren-yujbcrl-pajbb-anbnjalq-459[yslvg]\n" +
"oazegyqd-sdmpq-bxmefuo-sdmee-fqotzaxask-586[vfmnu]\n" +
"ugdgjxmd-jsttal-ksdwk-632[hfjix]\n" +
"aietsrmdih-gvcskirmg-tpewxmg-kveww-vigimzmrk-412[kfcim]\n" +
"drxevkzt-jtrmvexvi-ylek-uvgcfpdvek-685[vekdr]\n" +
"excdklvo-bkllsd-nozvyiwoxd-250[dlokv]\n" +
"uwtojhynqj-hfsid-wjxjfwhm-281[fqsmx]\n" +
"plolwdub-judgh-udeelw-uhfhlylqj-205[ludhe]\n" +
"oqnidbshkd-dff-zmzkxrhr-729[cvlkx]\n" +
"bknsykmdsfo-tovvilokx-bomosfsxq-328[boqly]\n" +
"dpotvnfs-hsbef-qspkfdujmf-cvooz-tijqqjoh-961[zmnyi]\n" +
"gspsvjyp-fyrrc-gsrxemrqirx-490[rsgpx]\n" +
"gifavtkzcv-szfyrqriuflj-wcfnvi-uvmvcfgdvek-139[zadfj]\n" +
"gsrwyqiv-kvehi-wgezirkiv-lyrx-wxsveki-490[alpzb]\n" +
"ykhknbqh-ydkykhwpa-zalhkuiajp-862[khayp]\n" +
"dmybmsuzs-yuxufmdk-sdmpq-bxmefuo-sdmee-fqotzaxask-586[nwikx]\n" +
"nwzekwypera-bhksan-nayaerejc-940[xnmta]\n" +
"wrs-vhfuhw-hjj-zrunvkrs-283[hrjsu]\n" +
"ajyqqgdgcb-pyzzgr-amlryglkclr-782[lozts]\n" +
"ohmnuvfy-jfumncw-alumm-womnigyl-mylpcwy-110[mqrgd]\n" +
"foadouwbu-suu-obozmgwg-792[hgkuj]\n" +
"wdjcvuvmyjpn-ytz-yzkgjthzio-109[jyztv]\n" +
"ucynmlgxcb-pyzzgr-qfgnngle-210[iftry]\n" +
"ymszqfuo-omzpk-oamfuzs-pqhqxabyqzf-872[qzfmo]\n" +
"clotzlnetgp-ojp-opawzjxpye-769[pnhtz]\n" +
"mhi-lxvkxm-yehpxk-ftgtzxfxgm-657[etajx]\n" +
"surmhfwloh-fkrfrodwh-uhfhlylqj-699[rkslj]\n" +
"iruzfrtkzmv-tyftfcrkv-kirzezex-841[emztq]\n" +
"bdavqofuxq-nmewqf-ogefayqd-eqdhuoq-352[jpmyv]\n" +
"bdavqofuxq-otaoaxmfq-xasuefuoe-326[aofqu]\n" +
"gpsxdprixkt-tvv-ldgzhwde-219[dgptv]\n" +
"pbeebfvir-rtt-bcrengvbaf-897[enlaq]\n" +
"jchipqat-gpqqxi-bpgztixcv-375[cnqyt]\n" +
"glrcplyrgmlyj-qaytclecp-fslr-pcqcypaf-574[clpyr]\n" +
"pejji-oqq-vyqscdsmc-640[qcjsd]\n" +
"houngfgxjuay-yigbktmkx-natz-xkykgxin-774[mszcw]\n" +
"ltpedcxots-jchipqat-gpqqxi-bpcpvtbtci-219[isgfv]\n" +
"gifavtkzcv-tyftfcrkv-drerxvdvek-659[vbdyz]\n" +
"vjpwncrl-mhn-orwjwlrwp-641[wrjln]\n" +
"vjpwncrl-ouxfna-bcxajpn-511[ydzfw]\n" +
"rzvkjiduzy-xviyt-xjvodib-adivixdib-187[idvxb]\n" +
"tinnm-suu-twbobqwbu-272[datjf]\n" +
"apuut-xviyt-vxlpdndodji-941[zrtso]\n" +
"jxdkbqfz-zixppfcfba-mixpqfz-doxpp-jxohbqfkd-705[fpxbd]\n" +
"zilqwikbqdm-lgm-kwvbiqvumvb-876[bqpme]\n" +
"jyddc-wgezirkiv-lyrx-wxsveki-256[sjntv]\n" +
"ahngzyzqcntr-qzaahs-zbpthrhshnm-963[fzvai]\n" +
"ksodcbwnsr-qfmcusbwq-suu-qighcasf-gsfjwqs-350[wyezk]\n" +
"atyzghrk-igtje-iugzotm-jkyomt-462[ksuli]\n" +
"dwbcjkun-ajmrxjlcren-yujbcrl-pajbb-nwprwnnarwp-563[tjsqg]\n" +
"aoubshwq-dzoghwq-ufogg-aofyshwbu-896[hwcmz]\n" +
"apwmeclga-npmhcargjc-njyqrga-epyqq-rpyglgle-340[dgtsc]\n" +
"apwmeclga-aylbw-amyrgle-dglylagle-210[iumzy]\n" +
"ydjuhdqjyedqb-rkddo-sedjqydcudj-738[ycbmx]\n" +
"iuxxuyobk-xgjougizobk-pkrrehkgt-sgtgmksktz-644[pzsmw]\n" +
"bnmrtldq-fqzcd-bgnbnkzsd-vnqjrgno-521[nbdqg]\n" +
"wfruflnsl-gzssd-wjhjnansl-177[wtmsg]\n" +
"yhwooebeaz-ywjzu-klanwpekjo-680[eowaj]\n" +
"pynffvsvrq-cynfgvp-tenff-ernpdhvfvgvba-663[vbduy]\n" +
"zilqwikbqdm-ntwemz-uizsmbqvo-356[yhenq]\n" +
"jvsvymbs-zjhclunly-obua-jvuahputlua-721[uajlv]\n" +
"fhezusjybu-rqiauj-tufbeocudj-400[ecamb]\n" +
"ftzgxmbv-wrx-xgzbgxxkbgz-293[xgbzf]\n" +
"chnylhuncihuf-xsy-xypyfijgyhn-578[jigcy]\n" +
"vhkkhlbox-pxtihgbsxw-cxeeruxtg-wxlbzg-111[hsuty]\n" +
"foadouwbu-tzcksf-gozsg-246[ofgsu]\n" +
"xzwrmkbqtm-moo-nqvivkqvo-434[moqvk]\n" +
"gvaaz-cvooz-dpoubjonfou-415[mcnzb]\n" +
"pbafhzre-tenqr-enoovg-grpuabybtl-169[bktjl]\n" +
"uwtojhynqj-gzssd-ywfnsnsl-723[phguv]\n" +
"dlhwvupglk-zjhclunly-obua-klwhyatlua-227[luahk]\n" +
"vhkkhlbox-vhehkyne-vahvhetmx-ybgtgvbgz-215[hvbeg]\n" +
"qlm-pbzobq-gbiivybxk-lmboxqflkp-809[blqik]\n" +
"forwcoqhwjs-qvcqczohs-ghcfous-792[mtuqn]\n" +
"eqpuwogt-itcfg-dwppa-fgrnqaogpv-570[gpafo]\n" +
"lxuxaodu-bljenwpna-qdwc-jwjuhbrb-121[rbqfd]\n" +
"ykhknbqh-xqjju-oanreyao-680[ahjkn]\n" +
"ugfkmewj-yjsvw-hdsklau-yjskk-kzahhafy-918[kahjs]\n" +
"gbc-frperg-fpniratre-uhag-fnyrf-897[dskta]\n" +
"myxcewob-qbkno-lexxi-wkxkqowoxd-770[spdoc]\n" +
"cqwdujys-fbqijys-whqii-huiuqhsx-998[uhebs]\n" +
"ckgvutofkj-igtje-iugzotm-rghuxgzuxe-774[gutei]\n" +
"excdklvo-lexxi-psxkxmsxq-302[ypsmx]\n" +
"mbiyqoxsm-dyz-combod-mkxni-mykdsxq-zebmrkcsxq-692[fnhpz]\n" +
"zlkprjbo-doxab-gbiivybxk-xkxivpfp-809[ydtxn]\n" +
"wdjcvuvmyjpn-ezggtwzvi-hvmfzodib-603[vzdgi]\n" +
"njmjubsz-hsbef-fhh-bobmztjt-649[mxkjw]\n" +
"wsvsdkbi-qbkno-oqq-ecob-docdsxq-796[rglok]\n" +
"htsxzrjw-lwfij-gfxpjy-fsfqdxnx-307[uyteb]\n" +
"wpuvcdng-ejqeqncvg-yqtmujqr-882[svamn]\n" +
"tagzsrsjvgmk-hdsklau-yjskk-ugflsafewfl-606[tysrn]\n" +
"kwtwznct-akidmvomz-pcvb-zmamizkp-200[skpom]\n" +
"dpmpsgvm-dboez-dpbujoh-fohjoffsjoh-311[fknst]\n" +
"rnqnyfwd-lwfij-hmthtqfyj-xytwflj-567[gzkol]\n" +
"zntargvp-pnaql-hfre-grfgvat-923[yijbm]\n" +
"dzczkrip-xiruv-treup-tfrkzex-drerxvdvek-347[vrmsu]\n" +
"ajyqqgdgcb-afmamjyrc-sqcp-rcqrgle-522[cqagr]\n" +
"pelbtravp-ohaal-erprvivat-715[jnbmz]\n" +
"irdgrxzex-sleep-ivrthlzjzkzfe-113[bmsnw]\n" +
"eqpuwogt-itcfg-tcddkv-fgxgnqrogpv-804[gtcdf]\n" +
"cvabijtm-moo-ivitgaqa-226[darfu]\n" +
"ytu-xjhwjy-xhfajsljw-mzsy-zxjw-yjxynsl-281[wzjeb]\n" +
"fkqbokxqflkxi-yxphbq-obxznrfpfqflk-809[dcasb]\n" +
"gokzyxsjon-sxdobxkdsyxkv-mkxni-ecob-docdsxq-276[zypso]\n" +
"ibghopzs-suu-kcfygvcd-402[cgsub]\n" +
"tfiifjzmv-srjbvk-uvjzxe-581[sovtj]\n" +
"gntmfefwitzx-gfxpjy-xmnuunsl-619[fnxgm]\n" +
"lgh-kwujwl-bwddqtwsf-vwhsjlewfl-788[tlejf]\n" +
"hjgbwuladw-wyy-ghwjslagfk-164[wgahj]\n" +
"nzwzcqfw-ojp-qtylyntyr-431[ynqtw]\n" +
"sbejpbdujwf-sbccju-vtfs-uftujoh-909[kujit]\n" +
"vhkkhlbox-wrx-ftkdxmbgz-241[uwzex]\n" +
"lahxpnwrl-bljenwpna-qdwc-cajrwrwp-381[yjzno]\n" +
"lugjuacha-jfumncw-alumm-jolwbumcha-838[uamcj]\n" +
"gvcskirmg-glsgspexi-jmrergmrk-828[smeyi]\n" +
"thnulapj-ihzrla-thyrlapun-955[ahlnp]\n" +
"sno-rdbqds-bzmcx-btrsnldq-rdquhbd-937[dbqrs]\n" +
"vdzonmhydc-eknvdq-dmfhmddqhmf-781[dmhfn]\n" +
"iehepwnu-cnwza-xqjju-ykjpwejiajp-368[jepwa]\n" +
"dfcxsqhwzs-dzoghwq-ufogg-cdsfohwcbg-974[gcdfh]\n" +
"sbqiiyvyut-tou-jhqydydw-608[okbzs]\n" +
"htsxzrjw-lwfij-gzssd-uzwhmfxnsl-801[nmtjq]\n" +
"hvbizodx-rzvkjiduzy-xviyt-yzqzgjkhzio-213[zivyd]\n" +
"ajmrxjlcren-ljwmh-lxjcrwp-bqryyrwp-745[kheat]\n" +
"vkppo-shoewudys-tou-udwyduuhydw-556[udowy]\n" +
"dpotvnfs-hsbef-dmbttjgjfe-gmpxfs-nbslfujoh-363[qapli]\n" +
"glrcplyrgmlyj-djmucp-qrmpyec-158[clmpr]\n" +
"emixwvqhml-xtiabqk-oziaa-wxmzibqwva-642[rkpba]\n" +
"qczcftiz-dzoghwq-ufogg-aofyshwbu-298[lmcuy]\n" +
"cvabijtm-zilqwikbqdm-akidmvomz-pcvb-nqvivkqvo-746[ynxzo]\n" +
"pkl-oaynap-acc-wjwhuoeo-134[jxlai]\n" +
"xjmmjndqz-kgvnodx-bmvnn-rjmfncjk-291[njmdk]\n" +
"ejpanjwpekjwh-nwxxep-nayaerejc-550[lisvd]\n" +
"htwwtxnaj-htsxzrjw-lwfij-hfsid-htfynsl-wjfhvznxnynts-541[hntwf]\n" +
"mbiyqoxsm-mkxni-mykdsxq-crszzsxq-770[zhowm]\n" +
"rmn-qcapcr-ucynmlgxcb-cee-pcqcypaf-886[cpaem]\n" +
"rtqlgevkng-ejqeqncvg-fgxgnqrogpv-466[zktns]\n" +
"fydelmwp-mfyyj-nfdezxpc-dpcgtnp-769[anfej]\n" +
"yuxufmdk-sdmpq-otaoaxmfq-pqbxakyqzf-742[ohxti]\n" +
"vxupkizork-igtje-xkgiwaoyozout-592[bmwjf]\n" +
"veqtekmrk-tvsnigxmpi-gerhc-gsexmrk-gywxsqiv-wivzmgi-802[dglps]\n" +
"nsyjwsfyntsfq-uqfxynh-lwfxx-ijuqtdrjsy-931[ymnhu]\n" +
"gifavtkzcv-avccpsvre-fgvirkzfej-841[ypigz]\n" +
"krxqjijamxdb-kdwwh-mnyjacvnwc-641[krnma]\n" +
"dszphfojd-ezf-sftfbsdi-805[fdszb]\n" +
"xmrrq-tmffq-lwuzfgdgyq-372[fqgmr]\n" +
"tagzsrsjvgmk-xdgowj-vwhsjlewfl-788[gjswl]\n" +
"lsyrkjkbnyec-mkxni-nofovyzwoxd-614[knoyx]\n" +
"dwbcjkun-mhn-bjunb-173[mykra]\n" +
"vhehkyne-vtgwr-nlxk-mxlmbgz-319[eghkl]\n" +
"bkzrrhehdc-bnqqnrhud-bzmcx-bnzshmf-otqbgzrhmf-677[xaszn]\n" +
"oxmeeuruqp-bxmefuo-sdmee-abqdmfuaze-248[udtec]\n" +
"jlidywncfy-mwupyhayl-bohn-uhufsmcm-500[yhmuc]\n" +
"xjmmjndqz-zbb-mzvxlpdndodji-239[djmzb]\n" +
"yuxufmdk-sdmpq-omzpk-qzsuzqqduzs-534[ofrpg]\n" +
"tfejldvi-xiruv-vxx-uvgrikdvek-659[cnesm]\n" +
"yaxsnlcrun-ajkkrc-anbnjalq-979[nmivs]\n" +
"tvsnigxmpi-ikk-wivzmgiw-880[agunv]\n" +
"mrxivrexmsrep-tpewxmg-kveww-viwievgl-698[evwim]\n" +
"nglmtuex-yehpxk-labiibgz-241[begil]\n" +
"zuv-ykixkz-ixeumktoi-igtje-iugzotm-aykx-zkyzotm-670[pjybl]\n" +
"forwcoqhwjs-dzoghwq-ufogg-difqvogwbu-272[xkwoz]\n" +
"ajyqqgdgcb-qaytclecp-fslr-bcqgel-886[mkvsi]\n" +
"myxcewob-qbkno-mkxni-mykdsxq-wkbuodsxq-770[zmijb]\n" +
"uwtojhynqj-kqtbjw-yjhmstqtld-333[jtqhw]\n" +
"wsvsdkbi-qbkno-lkcuod-dbksxsxq-406[biaoe]\n" +
"gpbepvxcv-rpcsn-rdpixcv-advxhixrh-895[dcwgp]\n" +
"muqfedyput-isqludwuh-xkdj-mehaixef-712[betdq]\n" +
"ckgvutofkj-inuiurgzk-xkgiwaoyozout-956[sazyo]\n" +
"wfruflnsl-uqfxynh-lwfxx-btwpxmtu-541[fxluw]\n" +
"qfmcusbwq-rms-igsf-hsghwbu-246[sbfgh]\n" +
"ynukcajey-nwxxep-qoan-paopejc-602[htmbv]\n" +
"ujqgywfau-uzgugdslw-jwkwsjuz-138[newms]\n" +
"yflexwxoalrp-zxkav-cfkxkzfkd-705[ctnsy]\n" +
"vjpwncrl-lqxlxujcn-mnyuxhvnwc-953[nawmz]\n" +
"willimcpy-wuhxs-lyuwkocmcncih-786[cilwh]\n" +
"mtzslklcozfd-clmmte-cpnptgtyr-119[tjkgv]\n" +
"xlrypetn-awldetn-rcldd-cplnbftdtetzy-795[tdlen]\n" +
"vkppo-rqiauj-huqsgkyiyjyed-452[yijkp]\n" +
"vxupkizork-lruckx-jkbkruvsktz-124[eumyz]\n" +
"diozmivodjivg-agjrzm-nzmqdxzn-915[otpfl]\n" +
"owshgfarwv-hdsklau-yjskk-klgjsyw-918[qcjim]\n" +
"zuv-ykixkz-igtje-iugzotm-zkinturume-202[plvqf]\n" +
"zlilocri-oxyyfq-bkdfkbbofkd-835[bswmn]\n" +
"ziuxioqvo-lgm-amzdqkma-798[maioq]\n" +
"xqvwdeoh-sodvwlf-judvv-ghyhorsphqw-517[hvdow]\n" +
"ovbunmneqbhf-enqvbnpgvir-onfxrg-qrfvta-507[nvbfq]\n" +
"gbc-frperg-pnaql-genvavat-351[pmzkq]\n" +
"eadalsjq-yjsvw-jsttal-suimakalagf-580[zjghy]\n" +
"rdadguja-rpcsn-rdpixcv-apqdgpidgn-245[dpagr]\n" +
"tbxmlkfwba-pzxsbkdbo-erkq-abpfdk-523[vifrq]\n" +
"ocipgvke-uecxgpigt-jwpv-ugtxkegu-544[abfsh]\n" +
"ovbunmneqbhf-zvyvgnel-tenqr-wryylorna-ybtvfgvpf-481[hxymg]\n" +
"pinovwgz-xjinphzm-bmvyz-agjrzm-ozxcijgjbt-681[cqlnu]\n" +
"tinnm-qobrm-ghcfous-220[hyczt]\n" +
"iuruxlar-yigbktmkx-natz-ykxboiky-748[kixya]\n" +
"bkzrrhehdc-bzmcx-bnzshmf-cdrhfm-209[hbcmr]\n" +
"gpsxdprixkt-tvv-uxcpcrxcv-973[xcpvr]\n" +
"forwcoqhwjs-rms-hfowbwbu-974[stzrm]\n" +
"zovldbkfz-fkqbokxqflkxi-mixpqfz-doxpp-cfkxkzfkd-705[tsmfo]\n" +
"vetllbybxw-lvtoxgzxk-angm-ftgtzxfxgm-371[sbemy]\n" +
"hwbba-ejqeqncvg-tgugctej-232[iyrqv]\n" +
"vqr-ugetgv-lgnnadgcp-wugt-vguvkpi-596[gvunp]\n" +
"xgvnndadzy-wpiit-yzndbi-343[rawyd]\n" +
"jxdkbqfz-oxyyfq-qbzeklildv-107[qbdfk]\n" +
"wlsiayhcw-luvvcn-mufym-656[jbvne]\n" +
"surmhfwloh-fdqgb-ghvljq-621[ymnve]\n" +
"mvkccspson-bkllsd-vklybkdybi-432[yscux]\n" +
"dszphfojd-sbccju-dvtupnfs-tfswjdf-129[itbfs]\n" +
"lsyrkjkbnyec-lexxi-crszzsxq-978[sxcek]\n" +
"qlm-pbzobq-mixpqfz-doxpp-zlkqxfkjbkq-211[satyb]\n" +
"bknsykmdsfo-nio-kmaescsdsyx-744[tspif]\n" +
"bpvctixr-rpcsn-rjhidbtg-htgkxrt-713[rtbcg]\n" +
"sebehvkb-rqiauj-udwyduuhydw-140[udbeh]\n" +
"zhdsrqlchg-fdqgb-hqjlqhhulqj-387[zptrs]\n" +
"qxdwpopgsdjh-rpcsn-sthxvc-635[nbixj]\n" +
"pualyuhapvuhs-msvdly-klzpnu-721[ulpah]\n" +
"sbqiiyvyut-shoewudys-isqludwuh-xkdj-jhqydydw-894[dysuh]\n" +
"wsvsdkbi-qbkno-lexxi-dbksxsxq-614[onzwh]\n" +
"ydjuhdqjyedqb-rqiauj-efuhqjyedi-894[ocdpe]\n" +
"kwzzwaqdm-ntwemz-wxmzibqwva-434[nwzml]\n" +
"qspkfdujmf-fhh-nbobhfnfou-571[zpyau]\n" +
"bxaxipgn-vgpst-tvv-detgpixdch-583[xwiac]\n" +
"qfmcusbwq-dfcxsqhwzs-xszzmpsob-fsqswjwbu-402[lstrx]\n" +
"dpmpsgvm-dboez-sfdfjwjoh-337[dfjmo]\n" +
"dzoghwq-ufogg-fsgsofqv-636[gfoqs]\n" +
"nzwzcqfw-dnlgpyrpc-sfye-qtylyntyr-509[milhd]\n" +
"xgsvgmotm-pkrrehkgt-vaxingyotm-176[jubcm]\n" +
"xgsvgmotm-jek-cuxqynuv-644[soxwn]\n" +
"cxy-bnlanc-lahxpnwrl-kdwwh-fxatbqxy-485[zamhj]\n" +
"irgyyolokj-inuiurgzk-sgtgmksktz-982[vzkrq]\n" +
"xgvnndadzy-xcjxjgvoz-xjiovdihzio-733[ozhyu]\n" +
"gvcskirmg-nippcfier-xiglrspskc-334[bastq]\n" +
"zlilocri-gbiivybxk-obxznrfpfqflk-367[ntyda]\n" +
"pyknyegle-pyzzgr-pcqcypaf-886[nxvzy]\n" +
"zhdsrqlchg-gbh-frqwdlqphqw-361[nqzts]\n" +
"kyelcrga-cee-yaosgqgrgml-808[izdqr]\n" +
"hplazytkpo-prr-cpnptgtyr-379[prtya]\n";
//kódok="hplazytkpo-prr-cpnptgtyr-379[prtya]\n";
    int idSum=0;
    String egySor="xxx";
    int id;
    String checksum;
    String roomCode;
    int[][] előfordulások=new int[123][2];//97-122-ig hasznalom: char  a-z. A 45-ot is, az a '-'
    int aktGyakoriságNdx;
    int[] számoltChecksum=new int[5];
    int egyformákElső;
    int egyformákUtolsó;
    int i=0;
    int sorokSzáma=0;
    System.out.println("Szting hossza:"+kódok.length());
    do{
      for (int j = 0; j < 123; j++) {
        //itt a 0-ás indexű oszlop a saját sorának számát kapja meg, ami a karakterkód.
        //Ez azért kell, mert a rendezésnél már a sorszám és a karakterkód nem fog megegyezni
        //mivel ezt a tombot rendezem később, ezért minden egyes sor feldolgozásánál inicializálni kell
        előfordulások[j][0]=j;
        előfordulások[j][1]=0;//ki kell nulláznom ezt is
      }
      //egy sor kinyerése
      egySor="";
      do{
        egySor+=kódok.substring(i, ++i);
      }while(i<kódok.length() && !kódok.substring(i-1, i).contentEquals("]"));
      //részSztingek meghatározása
      System.out.print(egySor+"*");
      sorokSzáma++;
      roomCode=egySor.split("\\d+\\[.+\\]")[0];
      id=Integer.decode(egySor.substring(egySor.lastIndexOf("-")+1,egySor.lastIndexOf("[")));
      System.out.print(id+"*");
      checksum=egySor.substring(egySor.lastIndexOf("[")+1, egySor.lastIndexOf("]"));
      System.out.println(checksum+"*");
      for (int j = 0; j < 5; j++) {//kinullázom a számoltChecksum tömböt
        számoltChecksum[j]=0;
      }
      for (int j = 0; j < roomCode.length(); j++) {//megszámolom, melyik karakter hányszor fordul elő
        előfordulások[roomCode.charAt(j)][1]++;
      }
      előfordulások[45][1]=0;//ennek (a '-'-nak) a gyakorisága nem érdekel, sőt, bekavarna
      //Az előfordulások kiválogatása:
      //lerendezem a tömböt előfordulások gyakorisága szerint. Csökkenőbe kell!!
      előfordulások=súlyozottRendezés(előfordulások, 1,"csökkenő");
      aktGyakoriságNdx=0;//most ez a leggyakoribb elem, mert csökkenőbe rendeztem
      int checksumNdx=0;
      do{
        //megnézem, hogy több egyforma gyakoriságú van-e
        egyformákElső=aktGyakoriságNdx;
        egyformákUtolsó=aktGyakoriságNdx;
        while((aktGyakoriságNdx<előfordulások.length-1)&&(előfordulások[aktGyakoriságNdx][1]==előfordulások[aktGyakoriságNdx+1][1])){
          egyformákUtolsó=++aktGyakoriságNdx;
        }
        if (egyformákElső!=egyformákUtolsó) {
          //ha az egyformákElső és az egyformákUtolsó nem egyezik, akkor több egyforma is van, melyeket le kell rendezni
          int[][] részTömb= Arrays.copyOfRange(előfordulások, egyformákElső, egyformákUtolsó+1);
          részTömb= súlyozottRendezés(részTömb, 0,"növekvő");
          //a résztömbből annyi elemet használok fel max, amennyi még kell a checksumba
          int ndx=0;
          while(checksumNdx<5 && ndx<részTömb.length){
            számoltChecksum[checksumNdx++]=részTömb[ndx++][0];
          }
          aktGyakoriságNdx++;
        }else
          számoltChecksum[checksumNdx++]=előfordulások[aktGyakoriságNdx++][0];
      }while(checksumNdx<5);
      if((számoltChecksumToString(számoltChecksum)).equals(checksum))
        idSum+=id;
      //Ha több egyforma előfordulási gyakoriság van, ezeket külön le kell rendezni:
        //Mivel erre van rendezve, addig lépkedek, amíg ugyanolyan gyakoriságot találok
        //legrosszabb eset legyen: 60 teljesen különböző karakter, azaz mindegyiknek egy a gyakorisága
        //Ehhez kell egy 60x2-es tömb, amibe töltöm ezeket a karaktereket, és előfordulásait
        //Ezt a tömböt lerendezem növekvőbe
        //Attól függően, mennyi karakter kell még a checksumhoz, az első n-t beleteszem az általam generált checksumba
      //Ha kell még a checksumba karakter, akkor folytatom a következő legggyakoribb karakterrel
      if(kódok.substring(i, i+1).equals("\n"))
        i++;
    }while(i<kódok.length());
    System.out.println("Sorok száma: "+sorokSzáma);
    System.out.println("Helyes kódok id-inek összege:"+idSum);
  }
}
